{
  "openapi": "3.0.0",
  "info": {
    "title": "Quimera API",
    "description": "API do sistema desenvolvido no bootcamp do Atlântico Academy",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:3333/"
    }
  ],
  "paths": {
    "/token/": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Criando token para autenticação do Usuário!",
        "description": "Essa rota é responsável pela criação do Token para o Usuário conseguir se autenticar!",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Token gerado com sucesso!"
          }
        },
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  },
                  "permission": {
                    "type": "string"
                  }
                },
                "example": {
                  "email": "pedro_oliverira@gmail.com",
                  "password": "13456"
                }
              }
            }
          }
        }
      }
    },
    "/users/": {
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "Cadastro de Usuários!",
        "description": "Essa rota é responsável pela criação de Usuários!",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Usuário cadastrado com sucesso!"
          },
          "400": {
            "description": "Esse Usuário já existe!"
          }
        },
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  },
                  "permission": {
                    "type": "string"
                  }
                },
                "example": {
                  "email": "pedro_oliverira@gmail.com",
                  "password": "13456"
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Busca por todos os Usuários!",
        "description": "Essa rota é responsável por buscar todos os Usuários cadastrados no banco!",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Busca todos os usuários",
            "content": {
              "application/json": {
                "example": [
                  {
                    "id": 1,
                    "email": "email@gmail.com",
                    "permission": "USER",
                    "created_at": "2022-06-18T14:04:38.614Z",
                    "updated_at": "2022-06-19T01:57:29.794Z"
                  },
                  {
                    "id": 2,
                    "email": "email2@gmail.com",
                    "permission": "USER",
                    "created_at": "2022-06-18T14:04:38.614Z",
                    "updated_at": "2022-06-19T01:57:29.794Z"
                  }
                ]
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/users/{id}": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Busca de Usuários pelo ID!",
        "description": "Essa rota é responsável por buscar Usuário pelo ID!",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "authorization",
            "in": "header",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Busca de Usuários pelo ID!",
            "content": {
              "application/json": {
                "example": [
                  {
                    "id": 1,
                    "email": "email@gmail.com",
                    "permission": "USER",
                    "created_at": "2022-06-18T14:04:38.614Z",
                    "updated_at": "2022-06-19T01:57:29.794Z"
                  },
                  {
                    "id": 2,
                    "email": "email2@gmail.com",
                    "permission": "USER",
                    "created_at": "2022-06-18T14:04:38.614Z",
                    "updated_at": "2022-06-19T01:57:29.794Z"
                  }
                ]
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Usuário não encontrado."
          },
          "500": {
            "description": "Erro interno!"
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      },
      "put": {
        "tags": [
          "Users"
        ],
        "summary": "Atualização de Usuário!",
        "description": "Essa rota é responsável pela atualização do Usuário!",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "authorization",
            "in": "header",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Usuário atualizado com sucesso!"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Usuário não encontrado."
          },
          "500": {
            "description": "Email deste usuário está invalido!"
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  },
                  "permission": {
                    "type": "string"
                  }
                },
                "example": {
                  "email": "pedro_oliverira@gmail.com",
                  "password": "13456"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Users"
        ],
        "summary": "Deleta um Usuário!",
        "description": "Essa rota é responsável por deletar um Usuário!",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "authorization",
            "in": "header",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Usuário deletado com sucesso!"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Erro interno!"
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/products/": {
      "post": {
        "tags": [
          "Products"
        ],
        "summary": "Cadastro de Produto!",
        "description": "Essa rota é responsável pela criação de Produtos!",
        "parameters": [
          {
            "name": "authorization",
            "in": "header",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Produto cadastrado com sucesso!"
          },
          "400": {
            "description": "Verifique se os campos necessários e as atribuições no exemplo estão corretas e tente novamente!"
          },
          "401": {
            "description": "Unauthorized"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "description": {
                    "type": "string"
                  },
                  "image": {
                    "type": "string"
                  },
                  "verified": {
                    "type": "boolean"
                  },
                  "userId": {
                    "type": "integer"
                  }
                },
                "example": {
                  "name": "macarrão",
                  "description": "teste",
                  "image": "teste",
                  "verified": false,
                  "userId": 1
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": [
          "Products"
        ],
        "summary": "Busca por todos os Produtos!",
        "description": "Essa rota é responsável por buscar todos os Produtos cadastrados no banco!",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Busca por todos os Produtos!",
            "content": {
              "application/json": {
                "example": [
                  {
                    "name": "macarrão",
                    "description": "gostoso",
                    "image": "teste",
                    "verified": false,
                    "userId": 1
                  },
                  {
                    "name": "cuscuz",
                    "description": "flocão",
                    "image": "teste",
                    "verified": false,
                    "userId": 1
                  }
                ]
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/products/{id}": {
      "get": {
        "tags": [
          "Products"
        ],
        "summary": "Busca de Produtos pelo ID!",
        "description": "Essa rota é responsável pela busca de Produto pelo ID!",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Busca de Produtos pelo ID!",
            "content": {
              "application/json": {
                "example": [
                  {
                    "name": "macarrão",
                    "description": "gostoso",
                    "image": "teste",
                    "verified": false,
                    "userId": 1
                  },
                  {
                    "name": "cuscuz",
                    "description": "flocão",
                    "image": "teste",
                    "verified": false,
                    "userId": 1
                  }
                ]
              }
            }
          },
          "400": {
            "description": "Solicitação Inválida"
          },
          "404": {
            "description": "Produto não encontrado!"
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      },
      "put": {
        "tags": [
          "Products"
        ],
        "summary": "Atualização de Produto!",
        "description": "Essa rota é responsável pela atualização do Produto!",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "authorization",
            "in": "header",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Produto atualizado com sucesso!"
          },
          "400": {
            "description": "Solicitação Inválida!"
          },
          "401": {
            "description": "Unauthorized"
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "description": {
                    "type": "string"
                  },
                  "image": {
                    "type": "string"
                  },
                  "verified": {
                    "type": "boolean"
                  },
                  "userId": {
                    "type": "integer"
                  }
                },
                "example": {
                  "name": "macarrão",
                  "description": "funcionou uhuu",
                  "image": "teste",
                  "verified": false,
                  "userId": 1
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Products"
        ],
        "summary": "Deleta um Produto!",
        "description": "Essa rota é responsável por deletar um Produto!",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "authorization",
            "in": "header",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Produto deletado com sucesso!"
          },
          "401": {
            "description": "Unauthorized"
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/feedbacks/": {
      "post": {
        "tags": [
          "Feedbacks"
        ],
        "summary": "Cadastro de Feedbacks!",
        "description": "Essa rota é responsável pelo cadastro de Feedbacks!",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Feedback cadastrado com sucesso!"
          },
          "400": {
            "description": "Verifique se os campos necessários e as atribuições no exemplo estão corretas e tente novamente!"
          }
        },
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "contents": {
                    "type": "string"
                  },
                  "productId": {
                    "type": "integer"
                  },
                  "userId": {
                    "type": "integer"
                  }
                },
                "example": {
                  "contents": "Esse produto contém açúcar",
                  "productId": 1,
                  "userId": 2
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": [
          "Feedbacks"
        ],
        "summary": "Busca por todos os Feedbacks!",
        "description": "Essa rota é responsável por buscar todos os Feedbacks cadastrados no banco!",
        "parameters": [
          {
            "name": "authorization",
            "in": "header",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Busca todos os usuários",
            "content": {
              "application/json": {
                "example": [
                  {
                    "contents": "Esse produto contém açúcar",
                    "productId": 1,
                    "userId": 2,
                    "created_at": "2022-06-18T14:04:38.614Z",
                    "updated_at": "2022-06-19T01:57:29.794Z"
                  }
                ]
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/feedbacks/{id}": {
      "get": {
        "tags": [
          "Feedbacks"
        ],
        "summary": "Busca de Feedbacks pelo ID!",
        "description": "Essa rota é responsável por buscar Feedback pelo ID!",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "authorization",
            "in": "header",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Busca de Feedbacks pelo ID!",
            "content": {
              "application/json": {
                "example": [
                  {
                    "contents": "Esse produto contém açúcar",
                    "productId": 1,
                    "userId": 2,
                    "created_at": "2022-06-18T14:04:38.614Z",
                    "updated_at": "2022-06-19T01:57:29.794Z"
                  }
                ]
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      },
      "put": {
        "tags": [
          "Feedbacks"
        ],
        "summary": "Atualização de Feedback!",
        "description": "Essa rota é responsável pela atualização do Feedback!",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "authorization",
            "in": "header",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Feedback atualizado com sucesso!"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Feedback não encontrado!"
          },
          "500": {
            "description": "Erro interno!"
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "contents": {
                    "type": "string"
                  },
                  "productId": {
                    "type": "integer"
                  },
                  "userId": {
                    "type": "integer"
                  }
                },
                "example": {
                  "contents": "Esse produto contém açúcar",
                  "productId": 1,
                  "userId": 2
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Feedbacks"
        ],
        "summary": "Deleta um Feedback!",
        "description": "Essa rota é responsável por deletar um Feedback!",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "authorization",
            "in": "header",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Feedback deletado com sucesso!"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Feedback não encontrado!"
          },
          "500": {
            "description": "Erro interno!"
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/brands/": {
      "post": {
        "tags": [
          "Brands"
        ],
        "description": "",
        "parameters": [],
        "responses": {}
      },
      "get": {
        "tags": [
          "Brands"
        ],
        "description": "",
        "parameters": [
          {
            "name": "authorization",
            "in": "header",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/brands/{id}": {
      "get": {
        "tags": [
          "Brands"
        ],
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "authorization",
            "in": "header",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "401": {
            "description": "Unauthorized"
          }
        }
      },
      "put": {
        "tags": [
          "Brands"
        ],
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "authorization",
            "in": "header",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "401": {
            "description": "Unauthorized"
          }
        }
      },
      "delete": {
        "tags": [
          "Brands"
        ],
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "authorization",
            "in": "header",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/ingredients/": {
      "post": {
        "tags": [
          "Ingredients"
        ],
        "summary": "Cadastro de Ingrediente!",
        "description": "Essa rota é responsável pelo cadastro de Ingredientes!",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Ingrediente cadastrado com sucesso!"
          }
        },
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  }
                },
                "example": {
                  "name": "Oléo de soja"
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": [
          "Ingredients"
        ],
        "summary": "Busca por todos os Ingredientes!",
        "description": "Essa rota é responsável por buscar todos os Ingredientes cadastrados no banco!",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Busca por todos os Ingredientes!",
            "content": {
              "application/json": {
                "example": [
                  {
                    "name": "Feijão",
                    "created_at": "2022-06-18T14:04:38.614Z",
                    "updated_at": "2022-06-19T01:57:29.794Z"
                  },
                  {
                    "name": "leite de cabra",
                    "created_at": "2022-06-18T14:04:38.614Z",
                    "updated_at": "2022-06-19T01:57:29.794Z"
                  }
                ]
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/ingredients/{id}": {
      "get": {
        "tags": [
          "Ingredients"
        ],
        "summary": "Busca de Ingredientes pelo ID!",
        "description": "Essa rota é responsável por buscar Ingrediente pelo ID!",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Busca por todos os Ingredientes!",
            "content": {
              "application/json": {
                "example": [
                  {
                    "name": "Feijão",
                    "created_at": "2022-06-18T14:04:38.614Z",
                    "updated_at": "2022-06-19T01:57:29.794Z"
                  },
                  {
                    "name": "leite de cabra",
                    "created_at": "2022-06-18T14:04:38.614Z",
                    "updated_at": "2022-06-19T01:57:29.794Z"
                  }
                ]
              }
            }
          },
          "404": {
            "description": "Ingrediente não encontrado."
          },
          "500": {
            "description": "Erro interno!"
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      },
      "put": {
        "tags": [
          "Ingredients"
        ],
        "summary": "Atualização de Ingredientes!",
        "description": "Essa rota é responsável pela atualização do Ingrediente!",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "authorization",
            "in": "header",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Ingrediente atualizado com sucesso!"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Ingrediente não encontrado."
          },
          "500": {
            "description": "Erro interno!"
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  }
                },
                "example": {
                  "name": "Oléo de soja"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Ingredients"
        ],
        "summary": "Deletar um Ingrediente!",
        "description": "Essa rota é responsável por deletar um Ingrediente!",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "authorization",
            "in": "header",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Ingrediente deletado com sucesso!"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Ingrediente não encontrado!"
          },
          "500": {
            "description": "Erro interno!"
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/categories/": {
      "post": {
        "tags": [
          "Categories"
        ],
        "description": "",
        "parameters": [],
        "responses": {}
      },
      "get": {
        "tags": [
          "Categories"
        ],
        "description": "",
        "parameters": [
          {
            "name": "authorization",
            "in": "header",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/categories/{id}": {
      "get": {
        "tags": [
          "Categories"
        ],
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "authorization",
            "in": "header",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "401": {
            "description": "Unauthorized"
          }
        }
      },
      "put": {
        "tags": [
          "Categories"
        ],
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "authorization",
            "in": "header",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "401": {
            "description": "Unauthorized"
          }
        }
      },
      "delete": {
        "tags": [
          "Categories"
        ],
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "authorization",
            "in": "header",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Product": {
        "type": "object",
        "properties": {
          "id": {
            "type": "number",
            "example": 1
          },
          "name": {
            "type": "string",
            "example": "Produto teste 1"
          },
          "description": {
            "type": "string",
            "example": "Teste de cadastro"
          },
          "image": {
            "type": "string",
            "example": "products/1/image.jpg"
          },
          "verified": {
            "type": "boolean",
            "example": false
          },
          "userId": {
            "type": "number",
            "example": 1
          },
          "brandId": {
            "type": "number",
            "example": 1
          },
          "created_at": {
            "type": "string",
            "example": "2022-06-19T02:00:13.930Z"
          },
          "updated_at": {
            "type": "string",
            "example": "2022-06-19T02:00:13.930Z"
          }
        }
      },
      "User": {
        "type": "object",
        "properties": {
          "id": {
            "type": "number",
            "example": 1
          },
          "email": {
            "type": "string",
            "example": "email@example.com"
          },
          "permission": {
            "type": "string",
            "example": "USER"
          },
          "created_at": {
            "type": "string",
            "example": "2022-06-18T14:04:38.614Z"
          },
          "updated_at": {
            "type": "string",
            "example": "2022-06-19T01:57:29.794Z"
          }
        }
      },
      "Feedback": {
        "type": "object",
        "properties": {
          "id": {
            "type": "number",
            "example": 1
          },
          "contents": {
            "type": "string",
            "example": "Produto muito bom"
          },
          "userId": {
            "type": "number",
            "example": 1
          },
          "productId": {
            "type": "number",
            "example": 1
          },
          "created_at": {
            "type": "string",
            "example": "2022-06-18T14:04:38.614Z"
          },
          "updated_at": {
            "type": "string",
            "example": "2022-06-19T01:57:29.794Z"
          }
        }
      },
      "Brand": {
        "type": "object",
        "properties": {
          "id": {
            "type": "number",
            "example": 1
          },
          "name": {
            "type": "string",
            "example": "Marca tal"
          },
          "created_at": {
            "type": "string",
            "example": "2022-06-18T14:04:38.614Z"
          },
          "updated_at": {
            "type": "string",
            "example": "2022-06-19T01:57:29.794Z"
          }
        }
      },
      "Ingredient": {
        "type": "object",
        "properties": {
          "id": {
            "type": "number",
            "example": 1
          },
          "name": {
            "type": "string",
            "example": "Ingrediente tal"
          },
          "created_at": {
            "type": "string",
            "example": "2022-06-18T14:04:38.614Z"
          },
          "updated_at": {
            "type": "string",
            "example": "2022-06-19T01:57:29.794Z"
          }
        }
      },
      "Category": {
        "type": "object",
        "properties": {
          "id": {
            "type": "number",
            "example": 1
          },
          "name": {
            "type": "string",
            "example": "Categoria tal"
          },
          "created_at": {
            "type": "string",
            "example": "2022-06-18T14:04:38.614Z"
          },
          "updated_at": {
            "type": "string",
            "example": "2022-06-19T01:57:29.794Z"
          }
        }
      }
    },
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}